name: "Moralis Deploy Action"
description: "Easy-to-use CI/CD workflows for deploying to Moralis Server"
author: "Yoseph Kurnia Soenggoro"
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload'
  color: 'green'
